### ISSUE TITLE
Sponge?

### ISSUE THREAD

**Issue by ryantheleach** [Multiverse/Multiverse-3#7]
Multiverse seems to be coded fairly platform independently, are there any plans on making it work on sponge if / when an API is available, and if so, do you have any input on how multiple worlds should be handled in the stock sponge API?

**Comment by kugick** [comment]
And now? What's going on?

**Comment by dumptruckman** [comment]
Well, I worked with the sponge team a bit to improve their world management API. I'm suppose to be working on an MV3 implementation for it but I've simply been too busy with work and school to do much.

**Comment by Rigby90** [comment]
What's the current state of MV3?

**Comment by elliot-labs** [comment]
@Rigby90 I would like to know this too.

Update: Spong is progressing very slowly. Spigot might be the way to go as their still up and running.

**Comment by Rigby90** [comment]
@dumptruckman

**Comment by dumptruckman** [comment]
The current state is that MV3 can create, delete, import, list, load and unload worlds for Bukkit. That means it is perfectly suitable for if all you want to do is have extra worlds loaded but not much beyond that. The properties system is partly implemented. The next steps there are to make the modify commands work and to make the properties have actual effects. Teleporting might work....
